CREATE TABLE IF NOT EXISTS batting(
    playerID text,
    yearID int,
    stint int,
    teamID text,
    leagueID text,
    games int,
    ab int,
    runs int,
    hits int,
    doubles int,
    triples int,
    homeruns int,
    rbi int,
    sb int,
    cs int,
    bb int,
    so int,
    ibb int,
    hbp int,
    sh int,
    sf int,
    gidp int,
    PRIMARY KEY (playerID, yearID, stint)
)